[package]
name = "folder-counter"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rfd = "0.15.1"
slint = "1.8.0"

[build-dependencies]
slint-build = "1.8.0"
