import { Button, VerticalBox } from "std-widgets.slint";

export component AppWindow inherits Window {
    width: 950px;
    height: 650px;
    in-out property <int> counter: 0;
    in-out property <string> fileDir: "";
    in-out property <bool> button_visible: true;
    in-out property <string> button_text: "点击选择文件夹";
    callback request-increase-value();
    callback request-file-dir();
    VerticalBox {
        GridLayout {
            Row {
                input := Text {
                    text: "文件夹内文件总数 : \{root.counter}";
                }
            }
        }
        TouchArea {
            Text {
                text: "文件夹地址是: \{root.fileDir}";
            }
            clicked => {
                root.counter = 0;
                root.fileDir = "";
                root.button_visible = true;
            }
        }
        button := Button {
            text: root.button_text;
            clicked => {
                if (!root.button_visible) {
                    button.text = "点击选择文件夹";
                    root.request-file-dir();
                } else {
                    button.text = "计算";
                    root.counter = 0;
                    root.request-increase-value();
                }
                root.button_visible = !root.button_visible;
            }
        }
    }
}
